// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Head         = require("next/head");
var Link         = require("next/link");
var ReasonReact  = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(href, _as, prefetch, replace, shallow, passHref, children) {
  return ReasonReact.wrapJsForReason(Link.default, {
              href: Js_undefined.from_opt(href),
              as: Js_undefined.from_opt(_as),
              prefetch: Js_undefined.from_opt(prefetch),
              replace: Js_undefined.from_opt(replace),
              shallow: Js_undefined.from_opt(shallow),
              passHref: Js_undefined.from_opt(passHref)
            }, children);
}

var Link$1 = /* module */[/* make */make];

function make$1(children) {
  return ReasonReact.wrapJsForReason(Head.default, { }, children);
}

var Head$1 = /* module */[/* make */make$1];

exports.Link = Link$1;
exports.Head = Head$1;
/* next/head Not a pure module */
